name: Build and Deploy frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Log in the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: frontend/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # deploy:
  #   runs-on: ubuntu-latest

  #   permissions:
  #     contents: read
  #     packages: write

  #   needs: build

  #   steps:
  #     - name: Deploy to GitHub Pages
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.HOST_USERNAME }}
  #         key: ${{ secrets.HOST_KEY }}
  #         port: ${{ secrets.HOST_PORT }}
  #         script: |
  #           cd ~/DOCKER/TP-web/frontend
  #           docker compose -f docker-compose.yml pull frontend
  #           docker compose -f docker-compose.yml down frontend
  #           docker compose -f docker-compose.yml up -d frontend
